### ISSUE TITLE
postLogoutRedirectUri not wired up by vue-msal

### ISSUE THREAD

**Issue by Agendum** [mvertopoulos/vue-msal#2]
vue-msal documentation indicates it supports 'postLogoutRedirectUri'. Unfortunately, vue-msal has not wired it up like it has other auth properties. I have been able to easily work-around this by simply:

```
beforeSignOut: function(ctx){
    ctx.lib.config.auth.postLogoutRedirectUri = ctx.auth.postLogoutRedirectUri;
}
```

**Comment by mvertopoulos** [comment]
Thanks for pointing this out. I am updating the plugin as necessary.
