### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Sodininkas** [mvertopoulos/vue-msal#4]
Hello, how correctly use this library with typescript? I would like to see vue.$msal.

I'm using like this

```
import { MSALBasic } from 'vue-msal/lib/src/types'
declare module 'vue/types/vue' {
  interface Vue {
    $msal: MSALBasic
  }
}
```
Is it correct?

Also if i import vue-msal like this:
`import msal from 'vue-msal/lib/plugin'`

I got many implicit errors

**Comment by mvertopoulos** [comment]
Hi!
I am sorry, but I am not sure I understand your question. Are you using vue.js with typescript support?
What kind of errors are you getting?
Could you share a complete example?

**Comment by Mohye77** [comment]
Hi @mvertopoulos ,

I am facing the same kind of issue, I am using vuejs with TypeScript but I can't find the typings nor the module corresponding to 'vue-msal'.
Here is the error in VS Code : 
`Could not find a declaration file for module 'vue-msal'. 'd:/dev/vue-feedback/node_modules/vue-msal/dist/plugin.js' implicitly has an 'any' type.
  Try 'npm install @types/vue-msal' if it exists or add a new declaration (.d.ts) file containing 'declare module 'vue-msal';'ts(7016)`

Here is my file `msal.ts`: 
`import Vue from 'vue';
import * as msal from 'vue-msal';

Vue.use(msal, {
    auth: {
        clientId: '<YOUR CLIENT ID HERE>'
    }
});
export default new msal();
`

Here is my file  `main.ts`:
`import Vue from 'vue'
import App from './App.vue'
import './registerServiceWorker'
import router from './router'
import store from './store'
import vuetify from './plugins/vuetify';
import msal from './plugins/msal';
import 'roboto-fontface/css/roboto/roboto-fontface.css'
import '@mdi/font/css/materialdesignicons.css'

Vue.config.productionTip = false

import './style.scss'

new Vue({
  router,
  store,
  vuetify,
  msal,
  render: h => h(App),

  created() {
    if (!this.$msal.isAuthenticated()) {
      this.$msal.signIn();
    }
  }
}).$mount('#app')`

Is there anything I'm missing?

**Comment by mvertopoulos** [comment]
Closing issue as there has been no answer for a while

**Comment by drovani** [comment]
I'm not sure if it's better to comment on this closed issue, or create a new one - but I, too, am having trouble getting this to work with Typescript.

My `main.ts` file looks like this:
```vue
import Vue from "vue";
import msal from "vue-msal";

Vue.use(msal, {
  auth: {
    clientId: "clientid"
  {
});

new Vue({
    //...
    created() {
        if (!this.$msal.isAuthenticated()) {
            this.$msal.signIn();
        }
    }
});
```

I get the error message of `Could not find a declaration file for module 'vue-msal'. Type 'npm install @types/vue-msal' if it exists or add a new declaration (.d.ts) file containing 'declare module 'vue-msal';'`. I have created the file `/src/vue-msal.shims.d.ts`:

```ts
declare module 'vue-msal';
```

Doing so resolves the first error. However, now I am receiving an error on the `this.$msal` line of `Property '$msal' does not exist on type 'CombinedVueInstance<Vue, Data, Methods, Computed, Readonly<Record<PropNames, any>>>'`. Based on a bit of Googling, the solution seems to be "[Augmenting Types for Use with Plugins](https://vuejs.org/v2/guide/typescript.html#Augmenting-Types-for-Use-with-Plugins)"

I created another shim file `/src/vue.msal.shims.d.ts` with the content:

```ts
import msal from 'vue-msal';

declare module 'vue/type/vue'{
  interface Vue{
    $msal: msal;
  }
}
```

This resolves the error I was getting in the `main.ts` file, but now I have an issue where  the `$msal: msal;` line in the shims file has an error of `Cannot use namespace 'msal' as a type.`. So now I'm lost as to what I need to put in this shim to make everything work. Do you have an pointers that might help?

Thank you.
