### ISSUE TITLE
Usage of method definition shorthand in mixin.js is breaking IE11

### ISSUE THREAD

**Issue by ZaradarDFDS** [mvertopoulos/vue-msal#5]
https://forum.vuejs.org/t/solved-ie11-script1003-expected-error/29843

**Comment by ZaradarDFDS** [comment]
export const mixin = {
    data: function() {
        return {
            msal: this.$msal.data
        }
    },
    created: function() {
        this.$watch('$msal.data', (value) => { this.msal = value; }, { deep: true });
    }
};

**Comment by ZaradarDFDS** [comment]
The above fix should do the trick. Cant fork your repo to make a branch to do a PR from :)

**Comment by mvertopoulos** [comment]
Thanks for reporting this
