### ISSUE TITLE
Failing on build

### ISSUE THREAD

**Issue by seanmerrifield** [mvertopoulos/vue-msal#6]
Hello, 

Thanks for setting this up! 

I still new to javascript and I seem to have trouble getting the build to succeed, although I am able to successfully launch the server in dev.  I get the error:

`
ERROR in build.js from UglifyJs
Unexpected token: name (msalPlugin) [./node_modules/vue-msal/dist/plugin.js:15,0][build.js:13535,6]
`

I'm using Vue version `2.5.11`.

**Comment by mvertopoulos** [comment]
Hi,

I haven't used Uglify but this is what I found from a quick search. The vue-msal plugin is transpiled to ES2015 (ES6).

Please take a look at [this issue](https://github.com/webpack/webpack/issues/2972) and more specifically [this comment](https://github.com/webpack/webpack/issues/2972#issuecomment-261705632).

Also, this is also mentioned on a [note](https://github.com/mishoo/UglifyJS2#note) at the start of Uglify's documentation.

Let me know if that helps.

**Comment by mvertopoulos** [comment]
Closing issue as there has been no answer for a while
