### ISSUE TITLE
callback after refreshing expired access token?

### ISSUE THREAD

**Issue by mihaiserban** [mvertopoulos/vue-msal#8]
I need to set the access token on axios instance, and i'm doing this onAuthentication. 
However I can't find a callback when the accessToken is refreshed.

on app mount/create, $msal.data.accessToken is empty.

**Comment by mvertopoulos** [comment]
> I need to set the access token on axios instance, and i'm doing this onAuthentication.
However I can't find a callback when the accessToken is refreshed.

There is an onToken callback in [auth options](https://github.com/mvertopoulos/vue-msal#auth-options-required), have you tried it?

> on app mount/create, $msal.data.accessToken is empty.

Please take a look at [this answer to a previous issue](https://github.com/mvertopoulos/vue-msal/issues/1#issuecomment-545430556)

Let me know if that helps.

**Comment by mihaiserban** [comment]
@mvertopoulos the [https://github.com/mvertopoulos/vue-msal/issues/1#issuecomment-545430556](answer) did the trick. used the watch feature to check for accessToken changes.

**Comment by mvertopoulos** [comment]
> I didn't manage to use onToken, it didn't seem to get called.

I will check the onToken issue.
